version: "2.1"
services:
  oressource:
    build: .
    depends_on:
      - database
    container_name: oressource_web
    ports:
      - 8787:80
    environment:
      - MYSQL_HOST=oressource_mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=oressource
      - MYSQL_USER=oressource
      - MYSQL_PASSWORD=password

  database:
    image: mariadb:10.6.16
    container_name: oressource_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=oressource
      - MARIADB_USER=oressource
      - MARIADB_PASSWORD=password
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql/oressource.sql:/docker-entrypoint-initdb.d/oressource.sql
